name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
  lint-checks:
    name: Run lint and format checks
    runs-on: ubuntu-latest
    steps:
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: cmd
