name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - run: make test
  lint-checks:
    name: Run lint and format checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
